input_data_path: "data/raw.csv"
metric_path: "models/LogisticRegression_metrics_train.json"
save_model: "models/LogisticRegression.pkl"
save_transformer: "models/LogisticRegression_transformer.pkl"

model_params:
  model_type: "LogisticRegression"
  random_state: 42
  penalty: 'l1'
  max_iter: 5000
  solver: "liblinear"
  

custom_transformer_params:
  use_custom_transformer: false


feature_params:
  one_hot_encoding_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "thal"
    - "ca"
    - "age"
  num_features:
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target: "condition"


splitting_params:
  test_size: 0.2
  random_state: 42
