name: Python-CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_project
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install -e .
      - name: Code analysis with pylint
        run: |
          pylint ./ml_project
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with unittest
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          coverage run tests/tests.py
      - name: Coverage report
        run: coverage report